// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1gPWeMl4DR4AgLjEw4TSOm3SrspjrVEg',
    appId: '1:393632820297:web:d5eb7e4593ab9b460fa398',
    messagingSenderId: '393632820297',
    projectId: 'newcomer-scu',
    authDomain: 'newcomer-scu.firebaseapp.com',
    storageBucket: 'newcomer-scu.appspot.com',
    measurementId: 'G-Q3FEF8ZXP9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQixUZGXVX7vz4OkANlu5lGox8yCRSYFo',
    appId: '1:393632820297:android:b781a38d3c4bcab60fa398',
    messagingSenderId: '393632820297',
    projectId: 'newcomer-scu',
    storageBucket: 'newcomer-scu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiA3SPa2a286GPB9zOWCy0yasbla5yCRI',
    appId: '1:393632820297:ios:7e9ff64fa03ec4d50fa398',
    messagingSenderId: '393632820297',
    projectId: 'newcomer-scu',
    storageBucket: 'newcomer-scu.appspot.com',
    iosBundleId: 'com.example.newcomer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiA3SPa2a286GPB9zOWCy0yasbla5yCRI',
    appId: '1:393632820297:ios:3bd129594b0769070fa398',
    messagingSenderId: '393632820297',
    projectId: 'newcomer-scu',
    storageBucket: 'newcomer-scu.appspot.com',
    iosBundleId: 'com.example.newcomer.RunnerTests',
  );
}
